name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          scp target/dscatalog-0.0.1-SNAPSHOT.jar user@your-public-ip:/path/to/deploy
          scp Dockerfile user@your-public-ip:/path/to/deploy
          scp docker-compose.yml user@your-public-ip:/path/to/deploy

      - name: Deploy with Docker Compose
        run: ssh user@your-public-ip 'cd /path/to/deploy && docker-compose up -d --build'